### ISSUE TITLE
This repo does not use AWSCC provider

### ISSUE THREAD

**Issue by lazzurs** [hashicorp/learn-terraform-aws-cloud-control#1]
This is clearly a copy and paste from the AWS provider.

This repo needs updated to use the new AWSCC provider.

**Comment by mbeacom** [comment]
@lazzurs The point of this repo is to use the guide here: https://developer.hashicorp.com/terraform/tutorials/aws/aws-cloud-control to add the provider and use it yourself.

**Comment by lazzurs** [comment]
My bad, I see this repo is exactly as it should be to go along with the tutorial.
